apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-green
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/rohithcj/argocd-kustomize-multienv.git
    path: apps/guestbook/overlays/ENV_NAME
    targetRevision: main